Soccer\TeamBundle\Entity\Team:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        nom:
            expose: true
        joueurs:
            expose: true
       
       