


    
    
Rest_User : 
  type : rest
  resource: "@SoccerUserBundle/Resources/config/routing_rest.yml"
  
  
    
Rest_Event : 
  type : rest
  resource: "@SoccerEventBundle/Resources/config/routing_rest.yml"
  

    
Rest_Team : 
  type : rest
  resource: "@SoccerTeamBundle/Resources/config/routing_rest.yml"
  
  
  
    
Rest_Comment : 
  type : rest
  resource: "@SoccerCommentBundle/Resources/config/routing_rest.yml"
  
  

    
Rest_Evolution : 
  type : rest
  resource: "@SoccerEvolutionBundle/Resources/config/routing_rest.yml"
  
  

    
Rest_Stat : 
  type : rest
  resource: "@SoccerStatBundle/Resources/config/routing_rest.yml"