


    
    
Rest_User : 
  type : rest
  resource: "@SubwayBuddyUserBundle/Resources/config/routing_rest.yml"
  
  
    
Rest_Event : 
  type : rest
  resource: "@SoccerEventBundle/Resources/config/routing_rest.yml"
  

    
Rest_Team : 
  type : rest
  resource: "@SoccerTeamBundle/Resources/config/routing_rest.yml"