soccer_evolution:
    resource: "@SoccerEvolutionBundle/Resources/config/routing.yml"
    prefix:   /

soccer_comment:
    resource: "@SoccerCommentBundle/Resources/config/routing.yml"
    prefix:   /

soccer_util:
    resource: "@SoccerUtilBundle/Resources/config/routing.yml"
    prefix:   /

soccer_team:
    resource: "@SoccerTeamBundle/Resources/config/routing.yml"
    prefix:   /

soccer_landing:
    resource: "@SoccerLandingBundle/Resources/config/routing.yml"
    prefix:   /

soccer_event:
    resource: "@SoccerEventBundle/Resources/config/routing.yml"
    prefix:   /


subway_buddy_user:
    resource: "@SoccerUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin


    
rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api
  
  
