<?php

namespace Proxies\__CG__\Soccer\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Notification extends \Soccer\UserBundle\Entity\Notification implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', '' . "\0" . 'Soccer\\UserBundle\\Entity\\Notification' . "\0" . 'message', '' . "\0" . 'Soccer\\UserBundle\\Entity\\Notification' . "\0" . 'date', '' . "\0" . 'Soccer\\UserBundle\\Entity\\Notification' . "\0" . 'userDemandeur', '' . "\0" . 'Soccer\\UserBundle\\Entity\\Notification' . "\0" . 'userRecepteur', '' . "\0" . 'Soccer\\UserBundle\\Entity\\Notification' . "\0" . 'event', '' . "\0" . 'Soccer\\UserBundle\\Entity\\Notification' . "\0" . 'match', '' . "\0" . 'Soccer\\UserBundle\\Entity\\Notification' . "\0" . 'type', '' . "\0" . 'Soccer\\UserBundle\\Entity\\Notification' . "\0" . 'status');
        }

        return array('__isInitialized__', 'id', '' . "\0" . 'Soccer\\UserBundle\\Entity\\Notification' . "\0" . 'message', '' . "\0" . 'Soccer\\UserBundle\\Entity\\Notification' . "\0" . 'date', '' . "\0" . 'Soccer\\UserBundle\\Entity\\Notification' . "\0" . 'userDemandeur', '' . "\0" . 'Soccer\\UserBundle\\Entity\\Notification' . "\0" . 'userRecepteur', '' . "\0" . 'Soccer\\UserBundle\\Entity\\Notification' . "\0" . 'event', '' . "\0" . 'Soccer\\UserBundle\\Entity\\Notification' . "\0" . 'match', '' . "\0" . 'Soccer\\UserBundle\\Entity\\Notification' . "\0" . 'type', '' . "\0" . 'Soccer\\UserBundle\\Entity\\Notification' . "\0" . 'status');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Notification $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setStatus(\Soccer\EventBundle\Entity\Status $status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessage($message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessage', array($message));

        return parent::setMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage', array());

        return parent::getMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvent(\Soccer\EventBundle\Entity\Event $event = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvent', array($event));

        return parent::setEvent($event);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvent', array());

        return parent::getEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatch(\Soccer\TeamBundle\Entity\Match $match = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatch', array($match));

        return parent::setMatch($match);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatch', array());

        return parent::getMatch();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(\Soccer\UserBundle\Entity\TypeNotification $type = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserDemandeur(\Soccer\UserBundle\Entity\User $userDemandeur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserDemandeur', array($userDemandeur));

        return parent::setUserDemandeur($userDemandeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserDemandeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserDemandeur', array());

        return parent::getUserDemandeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserRecepteur(\Soccer\UserBundle\Entity\User $userRecepteur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserRecepteur', array($userRecepteur));

        return parent::setUserRecepteur($userRecepteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserRecepteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserRecepteur', array());

        return parent::getUserRecepteur();
    }

}
