<?php

namespace Proxies\__CG__\Soccer\TeamBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserMatch extends \Soccer\TeamBundle\Entity\UserMatch implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', '' . "\0" . 'Soccer\\TeamBundle\\Entity\\UserMatch' . "\0" . 'match', '' . "\0" . 'Soccer\\TeamBundle\\Entity\\UserMatch' . "\0" . 'user', '' . "\0" . 'Soccer\\TeamBundle\\Entity\\UserMatch' . "\0" . 'buts', '' . "\0" . 'Soccer\\TeamBundle\\Entity\\UserMatch' . "\0" . 'passeDecisives', '' . "\0" . 'Soccer\\TeamBundle\\Entity\\UserMatch' . "\0" . 'cartonsRouge', '' . "\0" . 'Soccer\\TeamBundle\\Entity\\UserMatch' . "\0" . 'cartonsJaune');
        }

        return array('__isInitialized__', 'id', '' . "\0" . 'Soccer\\TeamBundle\\Entity\\UserMatch' . "\0" . 'match', '' . "\0" . 'Soccer\\TeamBundle\\Entity\\UserMatch' . "\0" . 'user', '' . "\0" . 'Soccer\\TeamBundle\\Entity\\UserMatch' . "\0" . 'buts', '' . "\0" . 'Soccer\\TeamBundle\\Entity\\UserMatch' . "\0" . 'passeDecisives', '' . "\0" . 'Soccer\\TeamBundle\\Entity\\UserMatch' . "\0" . 'cartonsRouge', '' . "\0" . 'Soccer\\TeamBundle\\Entity\\UserMatch' . "\0" . 'cartonsJaune');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserMatch $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\SubwayBuddy\UserBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatch(\Soccer\TeamBundle\Entity\Match $match)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatch', array($match));

        return parent::setMatch($match);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatch', array());

        return parent::getMatch();
    }

    /**
     * {@inheritDoc}
     */
    public function setButs($buts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setButs', array($buts));

        return parent::setButs($buts);
    }

    /**
     * {@inheritDoc}
     */
    public function getButs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getButs', array());

        return parent::getButs();
    }

    /**
     * {@inheritDoc}
     */
    public function addBut($nb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBut', array($nb));

        return parent::addBut($nb);
    }

    /**
     * {@inheritDoc}
     */
    public function setPasseDecisives($passes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasseDecisives', array($passes));

        return parent::setPasseDecisives($passes);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasseDecisives()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasseDecisives', array());

        return parent::getPasseDecisives();
    }

    /**
     * {@inheritDoc}
     */
    public function addPasseDecisives($nb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPasseDecisives', array($nb));

        return parent::addPasseDecisives($nb);
    }

    /**
     * {@inheritDoc}
     */
    public function setCartonsRouge($carton)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCartonsRouge', array($carton));

        return parent::setCartonsRouge($carton);
    }

    /**
     * {@inheritDoc}
     */
    public function getCartonsRouge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCartonsRouge', array());

        return parent::getCartonsRouge();
    }

    /**
     * {@inheritDoc}
     */
    public function addCartonsRouge($nb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCartonsRouge', array($nb));

        return parent::addCartonsRouge($nb);
    }

    /**
     * {@inheritDoc}
     */
    public function setCartonsJaune($carton)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCartonsJaune', array($carton));

        return parent::setCartonsJaune($carton);
    }

    /**
     * {@inheritDoc}
     */
    public function getCartonsJaune()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCartonsJaune', array());

        return parent::getCartonsJaune();
    }

    /**
     * {@inheritDoc}
     */
    public function addCartonsJaune($nb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCartonsJaune', array($nb));

        return parent::addCartonsJaune($nb);
    }

}
