<?php

namespace Soccer\TeamBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchRepository extends \Doctrine\ORM\EntityRepository
{
    
    /*
       public function findMatchBy($event, $user)
    {
      $query= $this
        ->createQueryBuilder('u')
         ->where("u.event= :event and u.user=:user ")
           ->setParameter(':event',$event)
           ->setParameter(':user',$user)
         ->orderBy('u.id', 'ASC')
        ->getQuery()
        ;
          try {
        return $query->getSingleResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    }
        
        
      ;
    }
    */
    
    
    
}


