<?php

namespace Soccer\TeamBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMatchRepository extends \Doctrine\ORM\EntityRepository
{
       public function findByMatchAndUser($match, $user)
    {
      $query= $this
        ->createQueryBuilder('u')
         ->where("u.match=:match and u.user=:user ")
           ->setParameter(':match',$match)
           ->setParameter(':user',$user)
         ->orderBy('u.id', 'ASC')
        ->getQuery()
        ;
          try {
        return $query->getSingleResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    }
        
        
      ;
    }
    
    
    
     public function findMatchFinished($user)
    {
      $query= $this
        ->createQueryBuilder('u')
        ->join("u.match","m")
        ->addSelect('m')
         ->where("u.user=:user and m.isFinished=1")
        
         ->setParameter(':user',$user)
         ->orderBy('u.id', 'ASC')
        ->getQuery()
        ;
          try {
        return $query->getResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    }
        
        
      ;
    }

}
