<?php

namespace Soccer\TeamBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMatchRepository extends \Doctrine\ORM\EntityRepository
{
    
    

}
