events:
    type:   rest
    resource:   "@SoccerEventBundle/Controller/EventController.php"
    

assigner_events:
    type:   rest
    resource:   "@SoccerEventBundle/Controller/AssignerEventController.php"
    
    
terrains:
    type:   rest
    resource:   "@SoccerEventBundle/Controller/TerrainController.php"
    
    