users:
    type:   rest
    resource:   "@SubwayBuddyUserBundle/Controller/UserController.php"
    
recherche:
    type:   rest
    resource:   "@SubwayBuddyUserBundle/Controller/RechercheController.php"
    
friends:
    type:   rest
    resource:   "@SubwayBuddyUserBundle/Controller/FriendsController.php"
    
notifications:
    type:   rest
    resource:   "@SubwayBuddyUserBundle/Controller/NotificationController.php"
    

    
website_test:
    path:     /test
    defaults: { _controller: SubwayBuddyUserBundle:Default:index }