Soccer\EventBundle\Entity\Event:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        nom:
            expose: true
        lieu:
            expose: true
        date:
            expose: true
        nombreJoueurs:
            expose: true
        admin:
            expose: true
        isGenerated:
            expose: true
       